lexik_jwt_authentication:
    secret_key: '%env(base64:JWT_SECRET_KEY_BASE64)%'
    public_key: '%env(base64:JWT_PUBLIC_KEY_BASE64)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 1209600
    user_id_claim: email
